
#Feature toggles; each of these will disable the registration of some content (items/enchants)
[cyclic]
	#Disable the endgame gear
	gemObsidianGear = true
	#Disable the cables aka pipes
	cables = true
	#Disable the 3 scaffolding blocks
	scaffolding = true
	#Disable 9 items, emerald armor and tools
	emeraldGear = true
	#Disable 5 netherbrick tools
	netherbrickGear = true
	#Disable the completely balanced climbing glove
	glove = true
	#Disable 6 charms (four basic, the ultimate, and the anti-gravity)
	charms = true
	#Disable all 11 enchantments
	enchantments = true
	#Disable 5 sandstone tools
	sandstoneGear = true
	#Disable the 3 boomerang items
	boomerangs = true
	#Disable the 3 spike blocks
	spikes = true
	#Disable 2 heart items that increase and decrease max health
	hearts = true
	#Disable the 5 carrot items that upgrade horses
	carrots = true

	[cyclic.command]
		#True means only players with OP can use this /cyclic command
		help = false
		#True means only players with OP can use this /cyclic command
		nbtprint = false
		#True means only players with OP can use this /cyclic command
		health = true
		#True means only players with OP can use this /cyclic command
		pingnether = false
		#True means only players with OP can use this /cyclic command
		gethome = false
		#True means only players with OP can use this /cyclic command
		worldspawn = true
		#True means only players with OP can use this /cyclic command
		home = true
		#True means only players with OP can use this /cyclic command
		hunger = true

	[cyclic.enchant]

		[cyclic.enchant.beheading]
			#Beheading enchant add player skin head drop, add any mob id and any skin
			BeheadingEntityMHF = ["minecraft:blaze:MHF_Blaze", "minecraft:cat:MHF_Ocelot", "minecraft:cave_spider:MHF_CaveSpider", "minecraft:chicken:MHF_Chicken", "minecraft:cow:MHF_Cow", "minecraft:enderman:MHF_Enderman", "minecraft:ghast:MHF_Ghast", "minecraft:iron_golem:MHF_Golem", "minecraft:magma_cube:MHF_LavaSlime", "minecraft:mooshroom:MHF_MushroomCow", "minecraft:ocelot:MHF_Ocelot", "minecraft:pig:MHF_Pig", "minecraft:zombie_pigman:MHF_PigZombie", "minecraft:sheep:MHF_Sheep", "minecraft:slime:MHF_Slime", "minecraft:spider:MHF_Spider", "minecraft:squid:MHF_Squid", "minecraft:villager:MHF_Villager", "minecraft:witch:MHF_Witch", "minecraft:wolf:MHF_Wolf", "minecraft:guardian:MHF_Guardian", "minecraft:elder_guardian:MHF_Guardian", "minecraft:snow_golem:MHF_SnowGolem", "minecraft:silverfish:MHF_Silverfish", "minecraft:endermite:MHF_Endermite"]

	[cyclic.logging]
		#Enable unblock info logs; very spammy
		info = true

	[cyclic.peat]
		#Chance that Peat Bog converts to Peat when wet (is multiplied by the number of surrounding water blocks)
		#Range: 0.0010000000474974513 ~ 1.0
		conversionChance = 0.07999999821186066

	[cyclic.energy]

		[cyclic.energy.cost]
			#Power per use
			#Range: 0 ~ 64000
			disenchanter = 1500
			#Power per repair 
			#Range: 0 ~ 64000
			anvil = 250
			#Power per use
			#Range: 0 ~ 64000
			dropper = 50
			#Power per use
			#Range: 0 ~ 64000
			peat_farm = 500
			#Power per use
			#Range: 0 ~ 64000
			miner = 10
			#Power per use
			#Range: 0 ~ 64000
			collector_fluid = 500
			#Power per recipe
			#Range: 0 ~ 64000
			melter = 5000
			#Power per use
			#Range: 0 ~ 64000
			harvester = 250
			#Power per use
			#Range: 0 ~ 64000
			uncraft = 1000
			#Power per use
			#Range: 0 ~ 64000
			forester = 50
			#Power per tick
			#Range: 0 ~ 64000
			beacon = 10
			#Power per use
			#Range: 0 ~ 64000
			crafter = 500
			#Power per recipe
			#Range: 0 ~ 64000
			solidifier = 5000

		[cyclic.energy.fuel]
			#Power gained burning one of this
			#Range: 1 ~ 64000
			peat_fuel_enriched = 1024
			#Power gained burning one of this
			#Range: 1 ~ 64000
			peat_fuel = 256

