
#####################################################################################
#Features with configurable properties are split into categories
#####################################################################################
[cyclic]

	#####################################################################################
	# Enchantment related configs
	#####################################################################################
	[cyclic.enchantment]

		[cyclic.enchantment.traveler]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.reach]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.beekeeper]
			#Beheading enchant add player skin head drop, add any mob id and any skin
			EntityMHF = ["minecraft:blaze:MHF_Blaze", "minecraft:cat:MHF_Ocelot", "minecraft:cave_spider:MHF_CaveSpider", "minecraft:chicken:MHF_Chicken", "minecraft:cow:MHF_Cow", "minecraft:enderman:MHF_Enderman", "minecraft:ghast:MHF_Ghast", "minecraft:iron_golem:MHF_Golem", "minecraft:magma_cube:MHF_LavaSlime", "minecraft:mooshroom:MHF_MushroomCow", "minecraft:ocelot:MHF_Ocelot", "minecraft:pig:MHF_Pig", "minecraft:zombie_pigman:MHF_PigZombie", "minecraft:sheep:MHF_Sheep", "minecraft:slime:MHF_Slime", "minecraft:spider:MHF_Spider", "minecraft:squid:MHF_Squid", "minecraft:villager:MHF_Villager", "minecraft:witch:MHF_Witch", "minecraft:wolf:MHF_Wolf", "minecraft:guardian:MHF_Guardian", "minecraft:elder_guardian:MHF_Guardian", "minecraft:snow_golem:MHF_SnowGolem", "minecraft:silverfish:MHF_Silverfish", "minecraft:endermite:MHF_Endermite"]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.experience_boost]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.launch]
			#Set false to disable Multi Jump enchantment
			enabled = true

		[cyclic.enchantment.ender]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.disarm]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.excavate]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.magnet]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.multishot]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.beheading]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.quickshot]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.venom]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.life_leech]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.curse]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.auto_smelt]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.growth]
			#Set false to disable enchantment
			enabled = true

		[cyclic.enchantment.step]
			#Set false to disable enchantment
			enabled = true

	#####################################################################################
	# Worldgen settings  
	#####################################################################################
	[cyclic.worldgen]
		#Does this generate in the world
		flower_cyan = true

	#####################################################################################
	# Block specific configs
	#####################################################################################
	[cyclic.blocks]

		#Ender shelf settings
		[cyclic.blocks.ender_shelf]
			#Controller Max distance to search (using manhattan distance)
			#Range: 1 ~ 256
			controller_distance = 64
			#Each shelf has five rows.  Set the number of books stored per row here
			#Range: 1 ~ 64
			books_per_row = 64

		[cyclic.blocks.anvil_magma]
			#Cost of magma fluid per action
			#Range: 1 ~ 64000
			fluid_cost = 100

		#Ender Anchor settings
		[cyclic.blocks.eye_teleport]
			#Maximum distance to activate
			#Range: 2 ~ 256
			range = 128
			#Exp cost on teleport
			#Range: 0 ~ 500
			exp = 0
			#Hunger cost on teleport
			#Range: 0 ~ 20
			hunger = 1
			#Tick delay between checks, faster checks can consume server resources (1 means check every tick; 20 means only check once per second)
			#Range: 1 ~ 20
			frequency = 5

		[cyclic.blocks.disenchanter]
			#Power per use disenchanter
			#Range: 0 ~ 64000
			energy_cost = 2500
			#Cost of (or payment for if negative) per enchanted book generated
			#Range: -1000 ~ 16000
			fluid_cost = 100

		#Uncrafter settings
		[cyclic.blocks.uncrafter]
			#When searching for a recipe, does it ignore all NBT values (such as enchantments, RepairCost, Damage, etc).  For example, if false it will not uncraft damaged or enchanted items
			nbt_ignored = false
			#Ticks used for each uncraft
			#Range: 1 ~ 9999
			ticks = 60
			#ITEM IDS HERE.  Block ALL recipes that output this item, no matter which recipe they use
			ignore_list = ["minecraft:elytra", "minecraft:tipped_arrow", "minecraft:magma_block", "minecraft:stick", "minecraft:*_dye", "spectrite:spectrite_arrow", "spectrite:spectrite_arrow_special", "techreborn:uumatter", "projecte:*"]
			#RECIPE IDS HERE.  Block these recipe ids from being reversed, but do not block all recipes for this output item
			ignore_recipes = ["botania:cobweb", "minecraft:magma_cream", "minecraft:beacon", "minecraft:stick_from_bamboo_item", "minecraft:netherite_ingot_from_netherite_block", "mysticalagriculture:essence*", "mysticalagriculture:farmland_till", "refinedstorage:coloring_recipes*", "forcecraft:transmutation*"]

		[cyclic.blocks.anvil_void]
			#Payment per void action, if not zero
			#Range: 0 ~ 16000
			fluid_cost = 25

		#Ender shelf settings
		[cyclic.blocks.sound]
			#Sound Recorder - how far out does it listen to record sounds
			#Range: 1 ~ 64
			radius = 8

		#Ender Trigger settings
		[cyclic.blocks.eye_redstone]
			#Maximum distance to activate
			#Range: 2 ~ 256
			range = 32
			#Tick delay between checks, faster checks can consume server resources (1 means check every tick; 20 means only check once per second)
			#Range: 1 ~ 20
			frequency = 5

		#Sprinkler settings
		[cyclic.blocks.sprinkler]
			#Tick rate.  20 will fire one block per second
			#Range: 1 ~ 20
			ticks = 20
			#Water consumption
			#Range: 0 ~ 1000
			water = 5

	#####################################################################################
	# Logging related configs
	#####################################################################################
	[cyclic.logging]
		#Unblock info logs; very spammy; can be useful for testing certain issues
		info = false

	#####################################################################################
	# Item specific configs
	#####################################################################################
	[cyclic.items]

		[cyclic.items.chorus_spectral]
			#Seconds of noClip per chorus_spectral
			#Range: 1 ~ 20000
			ticks = 600

		#Sack of Holding settings
		[cyclic.items.tile_transporter]
			#Block these from being picked up
			disable_pickup = ["minecraft:spawner", "parabox:parabox", "extracells:fluidcrafter", "extracells:ecbaseblock", "extracells:fluidfiller"]

		[cyclic.items.prospector]
			#Ore Prospector radius around player to search for ores
			#Range: 1 ~ 99
			range = 32

		[cyclic.items.chorus_flight]
			#Seconds of flight per chorus_flight
			#Range: 1 ~ 20000
			ticks = 1200

		#####################################################################################
		# Settings for varios charms (curios)
		#####################################################################################
		[cyclic.items.charms]
			#Boost given by item charm_luck
			#Range: 0 ~ 100
			luck = 10
			#Boost given by item charm_attackspeed
			#Range: 0.0 ~ 2.0
			attackspeed = 0.5
			#Boost given by item charm_speed
			#Range: 0.0 ~ 2.0
			speed = 0.5

			[cyclic.items.charms.charm_torch]
				#Light level limit for placing torches
				#Range: 0 ~ 15
				light_level = 9

			#####################################################################################
			# Caving Torch Charm settings
			#####################################################################################
			[cyclic.items.charms.caving_torch]
				#Light level at which to start placing down a torch
				#Range: 0 ~ 13
				light_limit = 7
				#Light level of the current block after placing down a torch. Must be greater than light_limit
				#Higher values means torches will be placed closer to you. Lower values means torches will overlap less,
				#but might result in small dark spots between torches
				#Range: 1 ~ 14
				light_target = 10
				#Whether to prioritise placing torches on walls
				prefer_walls = true
				#Which wall to place torches on when digging a 1-wide tunnel
				#True means left, False means right
				prefer_left_wall = false

		[cyclic.items.monster_ball]
			#Entity ids that cannot be picked up with the Monster all
			ignore_list = ["minecraft:ender_dragon", "minecraft:wither"]

		#Wand settings
		[cyclic.items.teleport_wand]
			#Maximum distance to activate
			#Range: 8 ~ 1024
			range = 256

		#Peat blocks
		[cyclic.items.peat]
			#Chance that Peat Bog converts to Peat when wet (is multiplied by the number of surrounding water blocks)
			#Range: 0.0010000000474974513 ~ 1.0
			conversionChance = 0.07999999821186066

		#Heart items
		[cyclic.items.heart]
			#Maximum number of hearts that can be attained (including initial 10)
			#Range: 1 ~ 200
			maximum = 100
			#Experience given when eating a poisoned heart
			#Range: 0 ~ 99999
			experience = 500

	#####################################################################################
	# Edit the permissions of all commands added by the mod.  false means anyone can use, true means only OP players can use  
	#####################################################################################
	[cyclic.command]
		#True means only players with OP can use this /cyclic command
		dev = false
		#True means only players with OP can use this /cyclic command
		ping = false
		#True means only players with OP can use this /cyclic command
		health = true
		#True means only players with OP can use this /cyclic command
		gethome = false
		#True means only players with OP can use this /cyclic command
		home = true
		#True means only players with OP can use this /cyclic command
		hunger = true

	#####################################################################################
	# Energy related configs for machines and items
	#####################################################################################
	[cyclic.energy]

		#####################################################################################
		#Energy cost for various machines, either per use of an action or per tick (twenty ticks per second).
		#####################################################################################
		[cyclic.energy.cost]
			#Power per repair anvil
			#Range: 0 ~ 64000
			anvil = 250
			#Power per use dropper
			#Range: 0 ~ 64000
			dropper = 50
			#Power per recipe in the packager
			#Range: 0 ~ 64000
			packager = 50
			#Power per use peat_farm
			#Range: 0 ~ 64000
			peat_farm = 500
			#Power per use miner
			#Range: 0 ~ 64000
			miner = 10
			#Power per use collector_fluid
			#Range: 0 ~ 64000
			collector_fluid = 500
			#Power per tick while in use
			#Range: 0 ~ 64000
			structure = 10
			#Power per use harvester
			#Range: 0 ~ 64000
			harvester = 250
			#Power per use uncraft
			#Range: 0 ~ 64000
			uncraft = 1000
			#Power per use forester
			#Range: 0 ~ 64000
			forester = 50
			#Power per tick while in use
			#Range: 0 ~ 64000
			beacon = 0
			#Power per use crafter
			#Range: 0 ~ 64000
			crafter = 500
			#Power per use user
			#Range: 0 ~ 64000
			user = 50

		[cyclic.energy.generator_food]
			#RF energy per tick generated while burning food in this machine
			#Range: 1 ~ 6400
			rf_per_tick = 60
			#This [factor * (item.food + item.saturation) = ticks] results in the number of ticks food will burn at. IE Bread has (5 + 0.6) with factor 100, will burn for 560 ticks.
			#Range: 1 ~ 6400
			ticks_per_food = 100

		[cyclic.energy.generator_fuel]
			#RF energy per tick generated while burning furnace fuel in this machine.  Burn time in ticks is the same as furnace values, so 1 coal = 1600 ticks
			#Range: 1 ~ 6400
			rf_per_tick = 80

