
#####################################################################################
#Features with configurable properties are split into categories
#####################################################################################
[cyclic]

	#####################################################################################
	# Enchantment related configs
	#####################################################################################
	[cyclic.enchantment]
		#Set false to disable enchantment
		traveler = true
		#Radius per level.  size around player to perform growth logic
		#Range: 1 ~ 16
		growthRadius = 2
		#Set false to disable enchantment
		reach = true
		#Set false to disable enchantment
		beekeeper = true
		#Set false to disable enchantment
		experience_boost = true
		#Set false to disable enchantment
		ender = true
		#Beheading enchant add player skin head drop, add any mob id and any skin
		beheadingEntityMHF = ["minecraft:blaze:MHF_Blaze", "minecraft:cat:MHF_Ocelot", "minecraft:cave_spider:MHF_CaveSpider", "minecraft:chicken:MHF_Chicken", "minecraft:cow:MHF_Cow", "minecraft:enderman:MHF_Enderman", "minecraft:ghast:MHF_Ghast", "minecraft:iron_golem:MHF_Golem", "minecraft:magma_cube:MHF_LavaSlime", "minecraft:mooshroom:MHF_MushroomCow", "minecraft:ocelot:MHF_Ocelot", "minecraft:pig:MHF_Pig", "minecraft:zombie_pigman:MHF_PigZombie", "minecraft:sheep:MHF_Sheep", "minecraft:slime:MHF_Slime", "minecraft:spider:MHF_Spider", "minecraft:squid:MHF_Squid", "minecraft:villager:MHF_Villager", "minecraft:witch:MHF_Witch", "minecraft:wolf:MHF_Wolf", "minecraft:guardian:MHF_Guardian", "minecraft:elder_guardian:MHF_Guardian", "minecraft:snow_golem:MHF_SnowGolem", "minecraft:silverfish:MHF_Silverfish", "minecraft:endermite:MHF_Endermite"]
		#Set false to disable enchantment
		venom = true
		#Set false to disable enchantment
		auto_smelt = true
		#Initial level drop rate.  So level I of enchant gives this % drop chance
		#Range: 1 ~ 100
		beheadingDrop = 20
		#Enchant level increase drop rate.  % = beheadingDrop + (level-1)*beheadingPerLevel
		#Range: 1 ~ 100
		beheadingPerLevel = 25
		#Set false to disable Multi Jump enchantment
		launch = true
		#Enchant level drop rate.  % = drop + (level-1)*drop
		#Range: 1 ~ 100
		disarmPercentPerLevel = 15
		#Set false to disable enchantment
		disarm = true
		#Set false to disable enchantment
		excavate = true
		#Set false to disable enchantment
		magnet = true
		#Set false to disable enchantment
		multishot = true
		#Set false to disable enchantment
		beheading = true
		#Set list of effects for Gloom enchant (cyclic:curse) to ignore and not use these
		gloomIgnored = ["minecraft:bad_omen", "minecraft:nausea", "botania:clear"]
		#Set false to disable enchantment
		quickshot = true
		#Mobs in this list cannot be disarmed and have their weapon stolen by the disarm enchantment
		disarmIngoredMobs = ["alexsmobs:mimicube"]
		#Set false to disable enchantment
		life_leech = true
		#Set false to disable gloom enchantment
		curse = true
		#Set false to disable enchantment
		growth = true
		#Set false to disable enchantment
		step = true

	#####################################################################################
	# Worldgen settings  
	#####################################################################################
	[cyclic.worldgen]
		#Does this generate in the world
		flower_cyan = true

	#####################################################################################
	# Block specific configs
	#####################################################################################
	[cyclic.blocks]
		#  Allows the dimensional Transfer Nodes to cross dimensions (no chunk loading is done, you have to do that on your own); This affects blocks cyclic:wireless_energy, cyclic:wireless_item, cyclic:wireless_fluid, cyclic:wireless_transmitter; If you change it to false it will only work if the target is in the same dimension.
		wireless_transfer_dimensional = true

		#Ender shelf settings
		[cyclic.blocks.ender_shelf]
			#Controller Max distance to search (using manhattan distance)
			#Range: 1 ~ 256
			controller_distance = 64
			#Each shelf has five rows.  Set the number of books stored per row here
			#Range: 1 ~ 64
			books_per_row = 64

		#Ender Anchor settings
		[cyclic.blocks.eye_teleport]
			#Maximum distance to activate
			#Range: 2 ~ 256
			range = 128
			#Exp cost on teleport
			#Range: 0 ~ 500
			exp = 0
			#Hunger cost on teleport
			#Range: 0 ~ 20
			hunger = 1
			#Tick delay between checks, faster checks can consume server resources (1 means check every tick; 20 means only check once per second)
			#Range: 1 ~ 20
			frequency = 5

		#Uncrafter settings
		[cyclic.blocks.uncrafter]
			#False will mean you cannot uncraft damaged repairable items. When searching for a recipe, does it ignore all NBT values (such as enchantments, RepairCost, Damage, etc).  For example, if false it will not uncraft damaged or enchanted items
			nbt_ignored = false
			#Ticks used for each uncraft
			#Range: 1 ~ 9999
			ticks = 60
			#ITEM IDS HERE.  Block ALL recipes that output this item, no matter which recipe they use. For example, if you add 'minecraft:stick' here, all recipes that craft into one or more sticks will be disabled (including two wooden planks).
			ignore_list = ["minecraft:elytra", "minecraft:tipped_arrow", "minecraft:magma_block", "minecraft:stick", "minecraft:*_dye", "spectrite:spectrite_arrow", "spectrite:spectrite_arrow_special", "techreborn:uumatter", "projecte:*"]
			#RECIPE IDS HERE.  Block these recipe ids from being reversed, but do not block all recipes for this output item
			ignore_recipes = ["botania:cobweb", "minecraft:magma_cream", "minecraft:beacon", "minecraft:stick_from_bamboo_item", "minecraft:netherite_ingot_from_netherite_block", "mysticalagriculture:essence*", "mysticalagriculture:farmland_till", "refinedstorage:coloring_recipes*", "forcecraft:transmutation*"]

		#Ender shelf settings
		[cyclic.blocks.sound]
			#Sound Recorder - how far out does it listen to record sounds
			#Range: 1 ~ 64
			radius = 8

		#Ender Trigger settings
		[cyclic.blocks.eye_redstone]
			#Maximum distance to activate
			#Range: 2 ~ 256
			range = 32
			#Tick delay between checks, faster checks can consume server resources (1 means check every tick; 20 means only check once per second)
			#Range: 1 ~ 20
			frequency = 5

		#battery settings
		[cyclic.blocks.battery]
			#RF/t charging rate for the battery item slot
			#Range: 1 ~ 6400000
			charge = 8000

		#Sprinkler settings
		[cyclic.blocks.sprinkler]
			#Tick rate.  20 will fire one block per second
			#Range: 1 ~ 20
			ticks = 20
			#Radius
			#Range: 1 ~ 32
			radius = 4
			#Water consumption
			#Range: 0 ~ 1000
			water = 5

		#experience_pylon settings
		[cyclic.blocks.experience_pylon]
			#Radius to pickup xp orbs
			#Range: 1 ~ 64
			radius = 16

		#fisher settings
		[cyclic.blocks.fisher]
			#Chance to Fish from nearby water.  Smaller values is slower fish
			#Range: 1.0E-5 ~ 0.999
			chance = 0.1
			#Radius to Fish from nearby water
			#Range: 1 ~ 32
			radius = 12

		#soundproofing settings
		[cyclic.blocks.soundproofing]
			#Radius of sound proofing (distance from each block that it will listen)
			#Range: 1 ~ 16
			radius = 6

	#####################################################################################
	# Logging related configs
	#####################################################################################
	[cyclic.logging]
		#Unblock info logs; very spammy; can be useful for testing certain issues
		info = false

	#####################################################################################
	#Fluid cost for various machines
	#####################################################################################
	[cyclic.fluid]
		#Cost of magma fluid per action
		#Range: 1 ~ 64000
		anvil_magma = 100
		#Cost of (or payment for if negative) per enchanted book generated
		#Range: -1000 ~ 16000
		disenchanter = 100
		#Payment per void action, if not zero
		#Range: 0 ~ 16000
		void_anvil = 25

	#####################################################################################
	# Item specific configs
	#####################################################################################
	[cyclic.items]
		#Entity ids that cannot be picked up with the Monster all
		monster_ball_ignore_list = ["minecraft:ender_dragon", "minecraft:wither"]

		#####################################################################################
		# Obsidian gear settings
		#####################################################################################
		[cyclic.items.obsidian]
			#Weapon damage
			#Range: 0.10000000149011612 ~ 99.0
			damage = 10.5
			#Damage Reduction
			#Range: 1 ~ 99
			chest = 11
			#Damage Reduction
			#Range: 1 ~ 99
			boots = 7
			#Armor toughness
			#Range: 0.10000000149011612 ~ 99.0
			toughness = 6.0
			#Damage Reduction
			#Range: 1 ~ 99
			helm = 7
			#Damage Reduction
			#Range: 1 ~ 99
			leg = 10

		#Sack of Holding settings
		[cyclic.items.tile_transporter]
			#Override chest placement when a 1/2 split chest is picked up, and set placed block as a singleton chests (prevents visual glitch of the open-sided half chest).  Set to false to restore old behavior and allow the split-chest placement.
			overrideChestSingle = true
			#Block these from being picked up
			disable_pickup = ["parabox:parabox", "extracells:fluidcrafter", "extracells:ecbaseblock", "extracells:fluidfiller", "exnihilosequentia:*", "refinedstorage:*", "tconstruct:seared_fuel_tank", "tconstruct:smeltery_controller", "tconstruct:seared_drain", "tconstruct:seared_fuel_gauge", "tconstruct:seared_ingot_tank", "tconstruct:seared_ingot_gauge", "tconstruct:seared_melter", "tconstruct:seared_heater", "tconstruct:scorched_drain", "tconstruct:scorched_duct", "tconstruct:scorched_chute", "tconstruct:foundry_controller", "tconstruct:scorched_alloyer", "rftoolspower:cell3", "rftoolspower:cell2", "rftoolspower:cell1", "rftoolspower:cell3", "rftoolspower:cell2", "rftoolspower:cell1"]

		#####################################################################################
		# scythe_harvest settings. note radius is halved while player is sneaking
		#####################################################################################
		[cyclic.items.scythe_harvest]
			#Radius defines how far it reaches (for example radius 6 is 13x13 square)
			#Range: 0 ~ 32
			radius = 6

		[cyclic.items.prospector]
			#Ore Prospector radius around player to search for ores
			#Range: 1 ~ 99
			range = 32

		#####################################################################################
		# Settings for varios charms (curios)
		#####################################################################################
		[cyclic.items.charms]
			#Boost given by item charm_luck
			#Range: 0 ~ 100
			luck = 10
			#Boost given by item charm_attackspeed
			#Range: 0.0 ~ 2.0
			attackspeed = 0.5
			#Boost given by item charm_speed
			#Range: 0.0 ~ 2.0
			speed = 0.5

			[cyclic.items.charms.charm_torch]
				#Light level limit for placing torches
				#Range: 0 ~ 15
				light_level = 9

			#####################################################################################
			# Caving Torch Charm settings
			#####################################################################################
			[cyclic.items.charms.caving_torch]
				#Light level at which to start placing down a torch
				#Range: 0 ~ 14
				light_limit = 7
				#Light level of the current block after placing down a torch. Must be greater than light_limit
				#Higher values means torches will be placed closer to you. Lower values means torches will overlap less,
				#but might result in small dark spots between torches
				#Range: 1 ~ 14
				light_target = 10
				#Whether to prioritise placing torches on walls
				prefer_walls = true
				#Which wall to place torches on when digging a 1-wide tunnel
				#True means left, False means right
				prefer_left_wall = false

		#apple_ender of settings
		[cyclic.items.apple_ender]
			#How many results the client will see
			#Range: 1 ~ 60
			printed = 5
			#Ignored Structures
			ignore = ["minecraft:shipwreck", "minecraft:mineshaft", "minecraft:stronghold", "minecraft:buried_treasure", "minecraft:pillager_outpost", "minecraft:village", "minecraft:nether_fossil"]

		#Heart items
		[cyclic.items.heart]
			#Maximum number of hearts that can be attained (including initial 10)
			#Range: 1 ~ 200
			maximum = 100
			#Experience given when eating a poisoned heart
			#Range: 0 ~ 99999
			experience = 500

		#####################################################################################
		# scythe_forage settings. note radius is halved while player is sneaking
		#####################################################################################
		[cyclic.items.scythe_forage]
			#Radius defines how far it reaches (for example radius 6 is 13x13 square)
			#Range: 0 ~ 32
			radius = 6

		#####################################################################################
		# spell_water settings
		#####################################################################################
		[cyclic.items.spell_water]
			#Radius defines how far it reaches
			#Range: 0 ~ 32
			radius = 3

		#####################################################################################
		# spell_ice settings
		#####################################################################################
		[cyclic.items.spell_ice]
			#Radius defines how far it reaches
			#Range: 0 ~ 32
			radius = 3

		#####################################################################################
		# scythe_leaves settings. note radius is halved while player is sneaking
		#####################################################################################
		[cyclic.items.scythe_leaves]
			#Radius defines how far it reaches (for example radius 6 is 13x13 square)
			#Range: 0 ~ 32
			radius = 6

		#####################################################################################
		# Edible chorus settings
		#####################################################################################
		[cyclic.items.chorus]
			#Seconds of flight per chorus_flight
			#Range: 1 ~ 20000
			flight = 1200
			#Seconds of noClip per chorus_spectral
			#Range: 1 ~ 20000
			ticks = 600

		#Wand settings
		[cyclic.items.teleport_wand]
			#Maximum distance to activate
			#Range: 8 ~ 1024
			range = 256

		#Peat blocks
		[cyclic.items.peat]
			#Chance that Peat Bog converts to Peat when wet (is multiplied by the number of surrounding water blocks)
			#Range: 0.0010000000474974513 ~ 1.0
			conversionChance = 0.07999999821186066

		#####################################################################################
		# scythe_brush settings. note radius is halved while player is sneaking
		#####################################################################################
		[cyclic.items.scythe_brush]
			#Radius defines how far it reaches (for example radius 6 is 13x13 square)
			#Range: 0 ~ 32
			radius = 6

		#####################################################################################
		# Emerald gear settings
		#####################################################################################
		[cyclic.items.emerald]
			#Weapon damage
			#Range: 0.10000000149011612 ~ 99.0
			damage = 4.5
			#Damage Reduction
			#Range: 1 ~ 99
			chest = 9
			#Damage Reduction
			#Range: 1 ~ 99
			boots = 4
			#Armor toughness
			#Range: 0.10000000149011612 ~ 99.0
			toughness = 3.0
			#Damage Reduction
			#Range: 1 ~ 99
			helm = 4
			#Damage Reduction
			#Range: 1 ~ 99
			leg = 7

	#####################################################################################
	# Edit the permissions of all commands added by the mod.  false means anyone can use, true means only OP players can use  
	#####################################################################################
	[cyclic.command]
		#True means only players with OP can use this /cyclic command
		dev = false
		#True means only players with OP can use this /cyclic command
		ping = false
		#True means only players with OP can use this /cyclic command
		health = true
		#True means only players with OP can use this /cyclic command
		gethome = false
		#True means only players with OP can use this /cyclic command
		home = true
		#True means only players with OP can use this /cyclic command
		hunger = true

	#####################################################################################
	# Energy related configs for machines and items
	#####################################################################################
	[cyclic.energy]

		#####################################################################################
		#Energy cost for various machines, either per use of an action or per tick (twenty ticks per second). Setting as zero (0) lets machine run for free
		#####################################################################################
		[cyclic.energy.cost]
			#Power per use disenchanter
			#Range: 0 ~ 64000
			disenchanter = 2500
			#Power per repair anvil
			#Range: 0 ~ 64000
			anvil = 250
			#Power per use dropper
			#Range: 0 ~ 64000
			dropper = 50
			#Power per recipe in the packager
			#Range: 0 ~ 64000
			packager = 50
			#Power per use peat_farm
			#Range: 0 ~ 64000
			peat_farm = 500
			#Power per use miner
			#Range: 0 ~ 64000
			miner = 10
			#Power per use collector_fluid
			#Range: 0 ~ 64000
			collector_fluid = 500
			#Power per tick while in use
			#Range: 0 ~ 64000
			structure = 10
			#Power per recipe melter
			#Range: 0 ~ 64000
			melter = 5000
			#Power per use harvester
			#Range: 0 ~ 64000
			harvester = 250
			#Power per use uncraft
			#Range: 0 ~ 64000
			uncraft = 1000
			#Power per use forester
			#Range: 0 ~ 64000
			forester = 50
			#Power per tick while in use
			#Range: 0 ~ 64000
			beacon = 0
			#Power per use crafter
			#Range: 0 ~ 64000
			crafter = 500
			#Power per use user
			#Range: 0 ~ 64000
			user = 0
			#Power per recipe solidifier
			#Range: 0 ~ 64000
			solidifier = 5000

		[cyclic.energy.generator_food]
			#RF energy per tick generated while burning food in this machine
			#Range: 1 ~ 6400
			rf_per_tick = 60
			#This [factor * (item.food + item.saturation) = ticks] results in the number of ticks food will burn at. IE Bread has (5 + 0.6) with factor 100, will burn for 560 ticks.
			#Range: 1 ~ 6400
			ticks_per_food = 100

		#####################################################################################
		# Fuel gained by consuming items
		#####################################################################################
		[cyclic.energy.fuel]
			#Power gained burning one of this
			#Range: 1 ~ 64000
			peat_fuel_enriched = 1024
			# Power gained burning one of this
			#Range: 1 ~ 64000
			peat_fuel = 256

		[cyclic.energy.generator_fuel]
			#RF energy per tick generated while burning furnace fuel in this machine.  Burn time in ticks is the same as furnace values, so 1 coal = 1600 ticks
			#Range: 1 ~ 6400
			rf_per_tick = 80

