
#Feature toggles; each of these will disable the registration of some content (items/enchants)
[cyclic]
	#Disable 5 sandstone tools
	sandstoneGear = true
	#Disable the endgame gear
	gemObsidianGear = true
	#Disable 9 items, emerald armor and tools
	emeraldGear = true
	#Disable 5 netherbrick tools
	netherbrickGear = true
	#Disable the completely balanced climbing glove
	glove = true
	#Disable 2 heart items that increase and decrease max health
	hearts = true
	#Disable the 5 carrot items that upgrade horses
	carrots = true
	#Disable 6 charms (four basic, the ultimate, and the anti-gravity)
	charms = true
	#Disable all 11 enchantments
	enchantments = true

	[cyclic.peat]
		#Chance that Peat Bog converts to Peat when wet (is multiplied by the number of surrounding water blocks)
		#Range: 0.0010000000474974513 ~ 1.0
		conversionChance = 0.07999999821186066

	[cyclic.energy]

		[cyclic.energy.cost]
			#Power gained burning one of this
			#Range: 1 ~ 64000
			anvil = 250
			#Power per recipe
			#Range: 1 ~ 64000
			solidifier = 5000
			#Power per recipe
			#Range: 1 ~ 64000
			melter = 5000

		[cyclic.energy.fuel]
			#Power gained burning one of this
			#Range: 1 ~ 64000
			peat_fuel_enriched = 1024
			#Power to repair one tick of durability
			#Range: 1 ~ 64000
			peat_fuel = 256

